openapi: 3.0.0
info:
  title: SMBC Bank Account Management API
  version: 1.0.0
paths:
  /accounts:
    get:
      summary: Get all bank accounts
      responses:
        '200':
          description: A list of bank accounts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
    post:
      summary: Create a new bank account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
      responses:
        '201':
          description: The created bank account
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
  /accounts/{accountId}:
    get:
      summary: Get a bank account by ID
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The requested bank account
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
    put:
      summary: Update a bank account by ID
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
      responses:
        '200':
          description: The updated bank account
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
    delete:
      summary: Delete a bank account by ID
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Bank account deleted
components:
  schemas:
    Account:
      type: object
      properties:
        accountId:
          type: string
        accountHolderName:
          type: string
        accountType:
          type: string
        balance:
          type: number
